from config import BETRAYAL, SILENCE, TWO_PLAYERS_SILENCE, TWO_PLAYERS_BETRAYAL, FIRST_PLAYER_SILENCE_SECOND_BETRAYAL, \
    FIRST_PLAYER_BETRAYAL_SECOND_SILENCE

DECISION_REVENUE = {SILENCE: {SILENCE: TWO_PLAYERS_SILENCE, BETRAYAL: FIRST_PLAYER_SILENCE_SECOND_BETRAYAL},
                    BETRAYAL: {SILENCE: FIRST_PLAYER_BETRAYAL_SECOND_SILENCE, BETRAYAL: TWO_PLAYERS_BETRAYAL}}
